name: Build and push to Cachix

on:
  push:
    branches: [ "main" ]

jobs:
  build-nix-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: n64-tools
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#unfloader
      - run: nix build .#toolchain
      - run: nix build .#chksum64
      - run: nix build .#n64tool
      - run: nix build .#n64sym
      - run: nix build .#bass_v14
      - run: nix build .#bass # should be no-op

  build-nix-macos-x64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: n64-tools
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#toolchain
      - run: nix build .#chksum64
      - run: nix build .#n64tool
      - run: nix build .#n64sym

  build-nix-macos-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: n64-tools
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#toolchain
      - run: nix build .#chksum64
      - run: nix build .#n64tool
      - run: nix build .#n64sym
      - run: nix build .#bass_v14
      - run: nix build .#bass # should be no-op
