name: Build and push to Cachix

on:
  push:
    branches: [ "main" ]

jobs:
  build-nix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # x64
          - macos-14 # arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: n64-tools
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#toolchain
      - run: nix build .#chksum64
      - run: nix build .#n64tool
      - run: nix build .#n64sym
      # - run: nix build .#bass_v14
      # - run: nix build .#bass # should be no-op

  # UNFLoader does not build on MacOS (missing ftd2xx dependency)
  build-unfloader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: n64-tools
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#unfloader
